GET http://localhost:5000/


### Sign In
POST http://localhost:5000/auth
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}


### Sign Out
DELETE http://localhost:5000/auth
Authorization: 
Content-Type: application/json

{
    "refreshToken": ""
}


### Get User Profile
GET http://localhost:5000/profile
Authorization: 


### Update User Profile
PATCH http://localhost:5000/profile
Authorization: 
Content-Type: application/json

{
    "email": "test@test.com",
    "firstName": "firstName",
    "lastName": "lastName",
    "gender": "male",
    "dateOfBirth": "1999-04-20"
}


### Refresh Token
POST http://localhost:5000/token
Content-Type: application/json

{
    "refreshToken": ""
}


### Get Active Sessions
POST http://localhost:5000/sessions
Authorization: 
Content-Type: application/json

{
    "refreshToken": ""
}


### Remove Active Sessions
DELETE http://localhost:5000/sessions/5fd98f152c86ce28fc11f432
Authorization: 
Content-Type: application/json

{
    "refreshToken": ""
}


### Change Password
PATCH http://localhost:5000/password
Authorization: 
Content-Type: application/json

{
    "currentPassword": "password",
    "newPassword": "password",
    "confirmPassword": "password"
}


### Get Users (only admin)
GET http://localhost:5000/users
Authorization: 


### Get Roles (only admin)
GET http://localhost:5000/roles
Authorization: 


### Validate Token
POST http://localhost:5000/validateToken
Content-Type: application/json

{
    "token": ""
}


###
